name: Release

on:
  push:
    tags:
      - [0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        php: [8.2, '8.3', '8.4', '8.5']
        tools: ['box:4.6']

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP runtime
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: ${{ matrix.tools }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: --prefer-dist

      - name: Download BOX Manifest Artifact
        env:
          BOX_MANIFEST_VERSION: ${{ vars.BOX_MANIFEST_VERSION || '4.2.0' }}
        run: |
          curl -Ls "https://github.com/llaville/box-manifest/releases/download/$BOX_MANIFEST_VERSION/box-manifest.phar" -o /usr/local/bin/box-manifest
          chmod +x /usr/local/bin/box-manifest

      - name: Build Release Artifact
        run: |
          box-manifest make build stub configure -r console-table.txt -r plain.txt -r sbom.json --output-stub stub.php --output-conf box.json.dist -vvv --ansi
          box compile -c box.json.dist -vvv --ansi

      - name: Create Release from current tag
        if: "github.ref_type == 'tag'"
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          draft: false
          body_path: ${{ github.workspace }}/.changes/${{ github.ref_name }}.md
          files: ${{ github.workspace }}/bin/phplint.phar
          fail_on_unmatched_files: true
          tag_name: ${{ github.ref_name }}
